# Generated by Django 5.1.4 on 2025-01-17 06:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=None, null=True, verbose_name='description'),
        ),
    ]
