# Generated by Django 5.1.4 on 2025-02-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0003_alter_blog_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
