# Generated by Django 5.1.4 on 2025-02-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0004_alter_blog_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.blog_post'),
        ),
    ]
